language: python
python:
  - 3.5

# Handle git submodules manually
git:
  submodules: false

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu
    $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - openssl aes-256-cbc -K $encrypted_c158cd588669_key -iv $encrypted_c158cd588669_iv -in keystore.p12.enc -out keystore.p12 -d

jobs:
  include:
    - stage: test
      script: true
    - stage: deploy
      # if: tag is present AND type = push
      script: docker run -v $(pwd):/usr/src/qfield  -e "STOREPASS=${STOREPASS}" -e "KEYNAME=${KEYNAME}" -e "KEYPASS=${KEYPASS}" opengisch/qfield-sdk /usr/src/qfield/scripts/docker-build.sh
      before_deploy: mv build-docker/out/build/outputs/apk/out-release-signed.apk build-docker/out/build/outputs/apk/qfield-${TRAVIS_TAG}.apk
      deploy:
        provider: releases
        api_key:
          secure: YOUR_API_KEY_ENCRYPTED
        file: build-docker/out/build/outputs/apk/qfield-${TRAVIS_TAG}.apk
        skip_cleanup: true
        on:
          tags: true
