version: '3'
services:
  qgis:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        qfield_test_docker_version: ${QFIELD_SDK_VERSION}
    tty: true
    volumes:
      - ${CI_BUILD_DIR}:/usr/src
