---
name: 🕴️ Style check

on:
  push:
    branches:
      - master
      - release-**
  pull_request:
    branches:
      - master
      - release-**
  issue_comment:
    types: [created]

jobs:
  astyle-check:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: khan/pull-request-comment-trigger@master
        id: indent-check
        if: ${{ github.event.issue.pull_request }}
        with:
          trigger: 'style police please'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - name: Check astyle
        run: |
          sudo apt install -y astyle
          find src/ -name '*.cpp' -o -name '*.h' | xargs ./scripts/astyle.sh
          find test/ -name '*.cpp' -o -name '*.h' | xargs ./scripts/astyle.sh
          if [ ! -z "$(git status --porcelain)" ]; then
            echo "::error::Indentation errors found (astyle)"
            echo "::group::Indentation changes"
            git diff
            echo "::endgroup"
          fi

      - uses: getsentry/action-git-diff-suggestions@main
        if: steps.indent-check.outputs.triggered != 'true'
        with:
          message: |
            Astyle suggested changes

            Accept them manually or add a comment with `style police please` to invoke some magic 🪄.

      - uses: EndBug/add-and-commit@v4
        if: steps.indent-check.outputs.triggered == 'true'
        with:
          author_name: Style police
          author_email: fairy@qfield.org
          message: 'Committing astyle changes'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
