name: Remove old artifacts

on:
  schedule:
    - cron: '20 * * * *'

jobs:
  remove_old_artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '10 minutes'
        # skip-tags: true
        skip-recent: 2
